version: '3.8'
name: biblio-service
services:
    mysql:
        image: mysql:5.7
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: docker
            MYSQL_DATABASE: biblio
        ports:
            - "3307:3306"
    # uncomment the following lines to load a dump file
    #        volumes:
    #            - ./db_dump.sql:/docker-entrypoint-initdb.d/init.sql

    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile
        restart: unless-stopped
        ports:
            - "8082:8082"
        volumes:
            - ./backend:/app:cached
            - backend-vendor:/app/vendor
            - backend-storage:/app/storage
        depends_on:
            - mysql
        environment:
            xdebug: false

    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile
        volumes:
            - ./frontend:/app
            - frontend-node-modules:/app/node_modules
        restart: unless-stopped
        ports:
            - "8083:8080"
        environment:
            - CHOKIDAR_USEPOLLING=true # Enable polling for file changes
            - WATCHPACK_POLLING=true
            - VITE_HMR_PORT=8080
volumes:
    backend-vendor:
    backend-storage:
    mysql-data:
    frontend-node-modules: