version: '3.8'
name: dei-local-dev
services:
    mysql:
        image: mysql:5.7
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: docker
        ports:
            - "13606:3606"
    # uncomment the following lines to load a dump file
    #        volumes:
    #            - ./db_dump.sql:/docker-entrypoint-initdb.d/init.sql

    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile
        restart: always
        ports:
            - "8081:8081"
        volumes:
            - ./backend/:/app/
        depends_on:
            - mysql

    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile
        volumes:
            - ./frontend:/app
            - /app/node_modules
        restart: always
        ports:
            - "8080:8080"
